server:
  port: 8085
  
spring:
  application:
    name: MUSIC-SERVICE
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 5

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://EUREKA:8761/eureka, http://localhost:8761/eureka
  instance:
    hostname: localhost