server:
  port: 8083
  
fileUpload:
  root: C:/Users/KID/FILE_UPLOAD_TEST
  
spring:
  application:
    name: RESOURCE-SERVICE
  servlet:
    multipart:
      max-file-size: 800MB
      max-request-size: 800MB
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://EUREKA:8761/eureka, http://localhost:8761/eureka
  instance:
    hostname: localhost