server:
  port: 8081
  
spring:
  application:
    name: AUTH-SERVICE
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 5 
   
logging:
  level:
    web: debug
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://EUREKA:8761/eureka, http://localhost:8761/eureka
      
  instance:
    prefer-ip-address: true
    hostname: localhost